- name: The first message
  hosts: all
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello Ansible World

- name: Create file
  hosts: all
  vars:
    simple_file: /tmp/simple-file-{{ ansible_date_time.iso8601 }}.txt
  tags:
    - tag1
  tasks:
    - name: Create file
      ansible.builtin.file:
        mode: "0775"
        path: "{{ simple_file }}"
        state: touch


- name: Write to file
  hosts: all
  vars:
    simple_file: /tmp/simple-file-{{ ansible_date_time.iso8601 }}.txt
  tags:
    - tag2
  tasks:
    - name: Write to file
      ansible.builtin.copy:
        mode: "0775"
        content: |
          Created by TheFormer: {{ ansible_date_time.iso8601 }}
        dest: "{{ simple_file }}"
